presta_bridge/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create] do
    resources :stores, only: [:new, :create, :destroy, :show], shallow: true do
      resources :products, shallow: false
    end
  end

  # Authenticated user dashboard page
  get '/settings', to: 'users#settings'

  # Session handling routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root to: 'sessions#new'
end

presta_bridge/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

presta_bridge/app/models/product.rb
class Product
  include ActiveModel::Model
  attr_accessor :name, :price, :id, :description

  validates_presence_of :name
  validates :price, presence: true, numericality: { greater_than: 0 }

  def to_request
    Prestashop::Mapper::Product.new(
      id_lang: 1,
      id_supplier: 1,
      reference: format('%s-%s', name.parameterize, rand(10000)),
      name: name,
      available_now: '',
      available_later: '',
      price: price
    )
  end
end

presta_bridge/app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user

  validates_presence_of :name
  validates :api_key, presence: true, length: { is: 32 }

  validate :valid_url?

  private

  def valid_url?
    uri = URI.parse(url)
    uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    errors.add(:url, 'Invalid URL given')
  end
end

presta_bridge/app/models/user.rb
class User < ApplicationRecord
  has_one :store

  validates_presence_of :name
  validates_presence_of :email

  has_secure_password
end

presta_bridge/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end
end

presta_bridge/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  cattr_accessor :catalog_class do
    Catalog
  end

  layout 'user'

  before_action :authorize

  def new
    @store_id = params[:store_id]
  end

  def show
    @product = catalog.find params[:id]
  end

  def index
    @store_name = store.name
    @products = catalog.all
  end

  def create
    product = Product.new(product_params)

    if product.valid?
      add_to_catalog product
    else
      flash[:error] = product.errors.full_messages
      redirect_to new_store_product_path(store)
    end
  end

  private

  def product_params
    params.require(:product)
          .permit(
            :name,
            :price
          )
  end

  def catalog
    catalog_class.new store
  end

  def add_to_catalog(product)
    if catalog.add(product)
      redirect_to store_products_path(store)
    else
      flash[:error] = ['Could not save the product']
      redirect_to new_store_product_path(store)
    end
  end

  def store
    current_user.store
  end
end

presta_bridge/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to settings_path if current_user
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to settings_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

presta_bridge/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  layout 'user'

  before_action :authorize

  def new;end

  def create
    store = build_store

    if store.save
      redirect_to settings_path
    else
      flash[:error] = store.errors.full_messages
      redirect_to new_user_store_path(current_user)
    end
  end

  def destroy
    if current_user.store.id == params[:id].to_i
      current_user.store.destroy
    end

    redirect_to settings_path
  end

  private

  def store_params
    params.require(:store)
          .permit(
            :name,
            :url,
            :api_key
          )
  end

  def build_store
    current_user.build_store store_params
  end

  def owned_by_current_user?

  end
end

presta_bridge/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: :settings

  def new; end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to settings_path
    else
      flash[:error] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def settings
    @store = current_user.store
    render layout: 'user'
  end

  private

  def user_params
    params.require(:user)
          .permit(
            :name,
            :email,
            :password,
            :password_confirmation
          )
  end
end

presta_bridge/app/helpers/application_helper.rb
module ApplicationHelper
end

presta_bridge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to PrestaBridge!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row main">
        <% flash.each do |key, messages| %>
          <div class="alert alert-danger col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2" role="alert">
            <button class="close" data-dismiss="alert">×</button>
            <h4>Oops!</h4>
            <% messages.each do |message| %>
              <p><%= message %></p>
            <% end %>
          </div>
        <% end %>
        <%= yield %>
		  </div>
	  </div>
  </body>
</html>

presta_bridge/app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to PrestaBridge!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <div id="sidebar-wrapper">
        <div class="panel panel-info">
          <div class="panel-heading">
            <div class="panel-title">Settings</div>
          </div>
          <div class="panel-body">
            <p>Welcome back, <%= current_user.name %>!</p>
          </div>
					<div class="list-group">
						<a href="#" class="list-group-item">
              Products
						</a>
					</div>
        </div>
      </div>
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <% flash.each do |key, messages| %>
                <div class="alert alert-danger col-md-6 col-sm-8" role="alert">
                  <button class="close" data-dismiss="alert">×</button>
                  <h4>Oops!</h4>
                  <% Array(messages).each do |message| %>
                    <p><%= message %></p>
                  <% end %>
                </div>
              <% end %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

presta_bridge/app/views/products/index.html.erb
<div class="col-md-6 col-sm-8">
    <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title"><%= @store_name %> Products</div>
        </div>
        <table class="table">
          <thead>
            <th>#</th>
            <th>Name</th>
            <th>Price</th>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td><%= product.id %></td>
                <td><%= link_to product.name, product_path(product.id) %></td>
                <td><%= product.price.round(2) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

presta_bridge/app/views/products/new.html.erb
<div class="col-md-6 col-sm-8">
    <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">New Product</div>
        </div>
        <div class="panel-body">
            <%= form_for :product, url: store_products_path(@store_id), class: 'form-horizontal' do |f| %>
                <div class="form-group">
                    <label for="name" class="cols-sm-2 control-label">Product Name</label>
                    <div class="cols-sm-10">
                        <%= f.text_field :name, class: 'form-control', required: true %>
                    </div>
                </div>
                <div class="form-group">
                    <label for="url" class="cols-sm-2 control-label">Product Price</label>
                    <div class="cols-sm-10">
                        <%= f.text_field :price, class: 'form-control', required: true %>
                    </div>
                </div>
                <%= f.submit "Create", class: 'btn btn-primary btn-lg btn-block login-button' %>
            <% end %>
        </div>
    </div>
</div>

presta_bridge/app/views/products/show.html.erb
<div class="col-md-6 col-sm-8">
    <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title"><%= @product.name %></div>
        </div>
        <div class="panel-body">
              <p><b>Price:</b> <%= @product.price %></p>
              <p><b>Description:</b> <%= @product.description %></p>
        </div>
    </div>
</div>

presta_bridge/app/views/stores/new.html.erb
<div class="col-md-6 col-sm-8">
    <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">New Store</div>
        </div>
        <div class="panel-body">
            <%= form_for :store, url: user_stores_path(current_user), class: 'form-horizontal' do |f| %>
                <div class="form-group">
                    <label for="name" class="cols-sm-2 control-label">Store Name</label>
                    <div class="cols-sm-10">
                        <%= f.text_field :name, class: 'form-control', required: true %>
                    </div>
                </div>
                <div class="form-group">
                    <label for="url" class="cols-sm-2 control-label">Store URL</label>
                    <div class="cols-sm-10">
                        <%= f.text_field :url, class: 'form-control', required: true %>
                    </div>
                </div>
                <div class="form-group">
                    <label for="api_key" class="cols-sm-2 control-label">API Key</label>
                    <div class="cols-sm-10">
                        <%= f.text_field :api_key, class: 'form-control', required: true %>
                    </div>
                </div>
                <%= f.submit "Create", class: 'btn btn-primary btn-lg btn-block login-button' %>
            <% end %>
        </div>
    </div>
</div>

presta_bridge/app/views/users/new.html.erb
<div class="main-login main-center col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="panel-title">Signup</div>
        </div>
        <div class="panel-body">
            <%= form_for :user, url: users_path, class: 'form-horizontal' do |f| %>
                <div class="form-group">
                    <label for="name" class="cols-sm-2 control-label">Your Name</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
                            <%= f.text_field :name, class: 'form-control', required: true %>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="cols-sm-2 control-label">Your Email</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i></span>
                            <%= f.text_field :email, class: 'form-control', required: true %>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="cols-sm-2 control-label">Your Password</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock" aria-hidden="true"></i></span>
                            <%= f.password_field :password, class: 'form-control', required: true %>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="cols-sm-2 control-label">Confirm Your Password</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock" aria-hidden="true"></i></span>
                            <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
                        </div>
                    </div>
                </div>

              <%= f.submit "Register", class: 'btn btn-primary btn-lg btn-block login-button' %>
            <% end %>
        </div>
    </div>
</div>

presta_bridge/app/views/users/settings.html.erb
<div class="col-md-6 col-sm-8">
    <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">Store Information</div>
        </div>
        <div class="panel-body">
          <% if @store %>
              <p><b>Name:</b> <%= @store.name %></p>
              <p><b>URL:</b> <%= @store.url %></p>
              <p><b>API Key:</b> <%= @store.api_key %></p>
              <p><b>Created At:</b> <%= @store.created_at %></p>

              <div class="btn-group">
                <%= link_to 'Add Product', new_store_product_path(@store), class: 'btn btn-success' %>
              </div>
              <div class="btn-group">
                <%= form_for @store, method: :delete do |f| %>
                    <%= f.submit 'Delete Store', class: 'btn btn-danger btn-md' %>
                <% end %>
              </div>
          <% else %>
            <h4>No stores configured yet</h4>
            <p>Click <%= link_to 'here', new_user_store_path(current_user.id) %> to configure it</p>
          <% end %>
        </div>
    </div>
</div>